# Generated by Django 2.2 on 2019-08-21 17:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190821_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_image_path),
        ),
    ]
