# Generated by Django 2.2 on 2019-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Musical'), ('SW', 'Sport wear'), ('OW', 'miscellaneous')], max_length=2),
        ),
    ]
